apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-go-deployment-SLOT_ID
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample
      slot: SLOT_ID
  template:
    metadata:
      name: go-docker
      labels:
        app: sample
        slot: SLOT_ID
    spec:
      containers:
        - image: gcr.io/PROJECT_ID/bluegreen-go:vBUILD_ID
          name: go-docker
---
apiVersion: v1
kind: Service
metadata:
  name: sample-go-service
spec:
  selector:
    app: sample
    slot: SLOT_ID
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80

